#!/bin/sh
# kFreeBSD do not accept scripts as interpreters, using #!/bin/sh and sourcing.
if [ true != "$INIT_D_SCRIPT_SOURCED" ] ; then
    set "$0" "$@"; INIT_D_SCRIPT_SOURCED=true . /lib/init/init-d-script
fi
### BEGIN INIT INFO
# Provides:          skeleton
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       This file should be used to construct scripts to be
#                    placed in /etc/init.d.  This example start a
#                    single forking daemon capable of writing a pid
#                    file.  To get other behavoirs, implemend
#                    do_start(), do_stop() or other functions to
#                    override the defaults in /lib/init/init-d-script.
### END INIT INFO

# Author: Thanh Luu <foobar@baz.org>
#
# Please remove the "Author" lines above and replace them
# with your own name if you copy and modify this script.

DESC="Daemon TCP printer"
DAEMON=/usr/bin/printserverd
PIDFILE=/var/lib/printserver/printserver.pid

depend() {
	need net
	after mysql
}

start() {
	ebegin "Starting Daemon TCP printer "
	start-stop-daemon --start --exec DAEMON -- -f -d 
	eend $?
}

stop() {
	# Par defaut
	#ebegin "Stoping Daemon TCP printer "
	#kill -s USR1 `cat /var/lib/printserver/printserver.pid`
	#eend $?

	# Stop via SIGKILL
	#ebegin "Stoping Daemon TCP printer "
	#start-stop-daemon --stop --signal KILL --pidfile PIDFILE
	#eend $?

	# Stop via SIGTERM
	ebegin "Stoping Daemon TCP printer "
	start-stop-daemon --stop --signal TERM --pidfile PIDFILE
	eend $?
}
