#!/bin/sh
# kFreeBSD do not accept scripts as interpreters, using #!/bin/sh and sourcing.
if [ true != "$INIT_D_SCRIPT_SOURCED" ] ; then
    set "$0" "$@"; INIT_D_SCRIPT_SOURCED=true . /lib/init/init-d-script
fi
### BEGIN INIT INFO
# Provides:          skeleton
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       This file should be used to construct scripts to be
#                    placed in /etc/init.d.  This example start a
#                    single forking daemon capable of writing a pid
#                    file.  To get other behavoirs, implemend
#                    do_start(), do_stop() or other functions to
#                    override the defaults in /lib/init/init-d-script.
### END INIT INFO

# Author: Foo Bar <foobar@baz.org>
#
# Please remove the "Author" lines above and replace them
# with your own name if you copy and modify this script.

DESC="Description of the service"
DAEMON=/home/user/insa/4ASTI/linux_admin/test

depend() {
	need net
}

start() {
	ebegin "Starting Daemon FTP printer - Thanh Luu"
	start-stop-daemon --start --exec /home/user/insa/4ASTI/linux_admin/test -- -f -d 
	eend $?
}

stop() {
	#ebegin "Stoping Daemon FTP printer - Thanh Luu"
	#kill -s USR1 /var/lib/q3ftpdaemon/daemon.pid
	#eend $?
	ebegin "Stoping Daemon FTP printer - Thanh Luu"
	kill -9 $(cat /var/lib/printserver/printserver.pid)
	eend $?
}
